---
- hosts: all
  tasks:
          - name: Install package ceph-common
            package:
                    name: ceph-common
                    state: present

          - name: Install another usefull packages
            apt:
                pkg:
                    - iotop
                    - htop
                    - nmap

