---
- hosts: all
  tasks:
          - name: deploy resolv.conf template
            template:
                    src: ~/k8s-supervisor-install/ansible/roles/resolv.conf/templates/resolv.conf
                    dest: /etc/resolv.conf
                    owner: root
                    group: root
                    mode: 0644
                    backup: yes
