---
- hosts: all
  tasks:
          - name: Edit kubelet env
            lineinfile:
                    path: /etc/kubernetes/kubelet.env
                    line: --cluster-dns=10.233.0.3 \
                    insertafter: KUBELET_ARGS=\"
                    state: present
           
          - name: Restart kubelet
            service:
                    name: kubelet
                    state: restarted 
