---
- hosts: all
  become: yes
  become_user: root

  gather_facts: no
  tasks:
        - name: Delete default routes
          script: ~/k8s-supervisor-install/ansible/roles/routes/scripts/delete.sh
        - name: Add persistent deletion of routes to system
          copy:
              src: ~/k8s-supervisor-install/ansible/roles/routes/scripts/delete.sh
              dest: /etc/networkd-dispatcher/routable.d
              owner: root
              group: root
              mode: '755'

